### ISSUE TITLE
Improve document title

### ISSUE THREAD

**Issue by thien-do** [thien-do/otf#18]
As noted by @kcjpop, the current title is some what too simple and confusing. Should have more meaningful info

![image](https://user-images.githubusercontent.com/5953369/123791287-72ddbe80-d909-11eb-8f1a-15dd3025ff1a.png)

**Comment by kcjpop** [comment]
Prolly also include the published/updating time of an article, so search engines can have a better insight.

**Comment by thien-do** [comment]
oh right, I did not notice it. Thank you.

Is there a way to have it automatically? (I'm using nextjs btw)

**Comment by kcjpop** [comment]
You know it better than me 🤷‍♂️ 😏

**Comment by thien-do** [comment]
Close as won't do, sorry
