### ISSUE TITLE
Feature Request: Add css reference

### ISSUE THREAD

**Issue by sairam** [thien-do/otf#9]
it would more helpful for developers looking at the website to copy snippets so that they can use in their own projects. 

If there is a section of css code (as a snippet) which the users can copy into their own site, it would help with developer experience on otf.show

**Comment by thien-do** [comment]
Thank you :D we will do this

**Comment by thien-do** [comment]
A note for whoever is going to implemented this (maybe me tomorrow) is that in many cases showing `font-feature-settings "${code}"` may not be enough, when the `font-variant-x` is preferred.

So basically we will also need to have the values for `font-variant-x`. For example, for `dlig`, it should show:

```css
font-variant-ligatures: discretionary-ligatures;
/* not font-feature-settings: "dlig" 1;*/
```
